---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# haiexplorer

<!-- badges: start -->
<!-- badges: end -->

The goal of haiexplorer is to ...

## Installation

You can install the development version of haiexplorer from [GitHub](https://github.com/) with:

``` r
# install.packages("pak")
pak::pak("ETC5523-2025/assignment-4-packages-and-shiny-apps-serl0001")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(haiexplorer)
## basic example code
```


In that case, don't forget to commit and push the resulting figure files, so they display on GitHub and CRAN.
```{r}
remotes::install_github(
  "ETC5523-2025/assignment-4-packages-and-shiny-apps-serl0001",
  subdir = "haiexplorer"
)
library(haiexplorer)
launch_app()

```

```{r}
rmarkdown::render("README.Rmd")
```

