name: pkgdown

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0          # <-- ensure full history for gh-pages push

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # <-- faster/more reliable package installs

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - name: Install R dependencies
        working-directory: haiexplorer
        run: |
          Rscript -e 'install.packages(c("remotes","pkgdown","devtools"))'
          Rscript -e 'remotes::install_deps(dependencies = TRUE)'

      - name: Build pkgdown site
        working-directory: haiexplorer
        run: Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = TRUE)'

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: haiexplorer/docs
